[package]
name = "voxane"
version = "0.1.0"
authors = ["Mark LeMoine <thatsgobbles@gmail.com>"]
edition = "2018"

[dependencies]
rustfft = "3"
cpal = "0.10.0"

[dev-dependencies]
assert_approx_eq = "1.1.0"
hound = "3.4.0"
